Setup

In [10]:
import os
os.chdir("..")
print(os.getcwd())

/Users/guilhermealmeidabusanello/Desktop/run_data_project

In [11]:
import duckdb
import pandas as pd

con = duckdb.connect()
print("DuckDB conectado!")

DuckDB conectado!

Visão geral da camada silver

In [12]:
df = con.execute("""
    SELECT
        start_time,
        distance_km,
        avg_pace_min_km / 60 AS pace_min_km,
        duration_min,
        calories,
        subjective_feeling,
        weather_condition,
        temperature_c
    FROM read_parquet('data/silver/runs.parquet')
    ORDER BY start_time
    LIMIT 10
""").df()

df

,start_time,distance_km,pace_min_km,duration_min,calories,subjective_feeling,weather_condition,temperature_c
0,2021-11-02 19:43:50-03:00,6.13,5.817500,35.67,468,good,night,25.0
1,2021-11-06 19:52:57-03:00,5.02,5.695167,28.57,379,awesome,NaN,NaN
2,2021-11-12 19:37:04-03:00,5.02,5.504667,27.62,373,good,NaN,NaN
3,2021-11-23 19:32:11-03:00,5.01,5.520000,27.67,374,good,NaN,NaN
4,2021-11-26 19:30:39-03:00,5.02,5.332000,26.77,367,awesome,NaN,NaN
5,2021-11-29 19:33:05-03:00,5.01,5.480167,27.47,374,awesome,sunny,21.0
6,2021-12-02 20:12:30-03:00,5.03,5.843667,29.40,376,awesome,night,24.0
7,2021-12-05 18:20:53-03:00,5.01,5.691833,28.53,376,good,cloudy,28.0
8,2021-12-11 17:07:36-03:00,5.10,5.482500,27.95,366,good,cloudy,28.0
9,2021-12-15 19:59:27-03:00,5.01,5.836000,29.25,374,awesome,night,27.0

Resumo anual

In [13]:
con.execute("""
    SELECT *
    FROM read_parquet('data/gold/yearly_summary.parquet')
    ORDER BY year
""").df()

,year,total_runs,total_km,avg_pace_min_km,total_calories,total_duration_h,avg_distance_km,longest_run_km
0,2021,13,73.38,342.77,5548,7.06,5.64,10.00
1,2022,89,530.84,353.57,41074,52.50,5.96,10.01
2,2023,75,419.26,351.92,32649,41.09,5.59,10.02
3,2024,63,324.06,347.27,24699,31.28,5.14,7.01
4,2025,56,353.33,340.19,27285,33.36,6.31,10.03
5,2026,9,53.17,331.63,4111,4.91,5.91,10.00

Evolução mensal de km

In [14]:
con.execute("""
    SELECT
        year_month,
        total_runs,
        total_km,
        avg_pace_min_km / 60 AS avg_pace_min_km
    FROM read_parquet('data/gold/monthly_summary.parquet')
    ORDER BY year_month
""").df()

   year_month  total_runs  total_km  avg_pace_min_km
0     2021-11           6     31.21         5.558333
1     2021-12           7     42.17         5.845500
2     2022-01           8     44.13         5.762000
3     2022-02          10     53.08         5.866000
4     2022-03           8     40.10         5.679500
5     2022-04           5     25.04         5.750500
6     2022-05           7     34.25         5.678000
7     2022-06           6     32.02         5.801167
8     2022-07           6     30.02         5.827000
9     2022-08           8     48.02         5.807333
10    2022-09           6     44.05         6.098000
11    2022-10           8     53.07         6.010000
12    2022-11           8     55.04         6.113667
13    2022-12           9     72.02         6.218833
14    2023-01           8     60.08         6.003000
15    2023-02           8     51.43         5.881167
16    2023-03           7     45.01         5.928000
17    2023-04           6     30.94         5.831500
18    2023-05           7     37.09         5.803333
19    2023-06           4     20.03         5.763500
20    2023-07           6     30.07         5.839000
21    2023-08           6     30.20         5.938667
22    2023-09           6     29.19         6.140833
23    2023-10           5     25.06         5.807500
24    2023-11           5     25.07         5.790833
25    2023-12           7     35.09         5.594833
26    2024-01           9     47.12         5.754500
27    2024-02           7     37.06         5.796333
28    2024-03           8     40.11         5.666333
29    2024-04           7     37.05         5.765333
30    2024-05           4     20.05         5.676000
31    2024-06           4     20.05         5.686000
32    2024-07           3     15.02         5.749500
33    2024-08           5     25.01         5.800167
34    2024-09           2     10.00         5.704000
35    2024-10           4     19.58         6.019000
36    2024-11           5     25.00         5.999500
37    2024-12           5     28.01         5.879667
38    2025-01           9     47.57         5.723500
39    2025-02           3     17.00         5.976167
40    2025-03           7     37.03         5.795333
41    2025-04           6     39.52         5.748000
42    2025-05           5     30.98         5.456667
43    2025-06           2     10.01         5.902667
44    2025-07           4     24.03         5.715333
45    2025-08           4     28.05         5.656000
46    2025-09           4     31.99         5.513667
47    2025-10           3     23.52         5.491667
48    2025-11           5     37.08         5.466833
49    2025-12           4     26.55         5.644500
50    2026-01           4     25.10         5.468167
51    2026-02           5     28.07         5.574500

Melhores marcas

In [15]:
con.execute("""
    SELECT *
    FROM read_parquet('data/gold/personal_bests.parquet')
""").df()

  distance  best_time_min       date  pace_min_km  distance_km
0      1km           4.54 2025-09-22       303.52          5.0
1      1mi           7.32 2025-09-22       303.52          5.0
2      5km          25.28 2025-09-22       303.52          5.0